# Generated by Django 3.0.5 on 2022-06-01 10:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mathematics', 'Mathematics'), ('Physical Science', 'Physical Science'), ('English', 'English'), ('Accounting', 'Accounting'), ('Information Technology', 'Information Technology'), ('Chemistry', 'Chemistry'), ('Economics', 'Economics'), ('Programming', 'Programming'), ('Engineering', 'Engineering'), ('Bussiness', 'Business'), ('Geography', 'Geography'), ('History', 'History'), ('Statistics', 'Statistics'), ('Marketing', 'Marketing'), ('Law', 'Law')], default='Other', max_length=167),
        ),
    ]
