# Generated by Django 3.0.5 on 2022-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220601_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='id_num',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AddField(
            model_name='tutors',
            name='id_num',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='gender',
            field=models.CharField(default='Other', max_length=10),
        ),
    ]
