# Generated by Django 3.0.5 on 2022-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220615_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='price_range',
            field=models.CharField(choices=[(1, 'Under R50'), (2, 'R50 to R100'), (3, 'R100 to R150'), (4, 'R150 to R200'), (5, 'R200 & Above')], default='-----', max_length=50),
        ),
    ]
