# Generated by Django 3.0.5 on 2022-06-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220604_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
