# Generated by Django 3.0.5 on 2022-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220605_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='img',
            field=models.ImageField(blank=True, default='0x0.jpg', null=True, upload_to=''),
        ),
    ]
