# Generated by Django 3.0.5 on 2022-06-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220605_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='location',
            field=models.CharField(choices=[('Other', 'Other'), ('GAUTENG,Soshanguve', 'GAUTENG,Soshanguve'), ('GAUTENG,Pretoria', 'GAUTENG,Pretoria'), ('GAUTENG,Centurion', 'GAUTENG,Centurion'), ('LIMPOPO,Bela Bela', 'LIMPOPO,Bela Bela'), ('LIMPOPO,Modimolle', 'LIMPOPO,Modimolle'), ('LIMPOPO,Polokwane', 'LIMPOPO,Polokwane'), ('CAPE TOWN', 'CAPE TOWN'), ('DURBAN', 'DURBAN')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='location',
            field=models.CharField(choices=[('Other', 'Other'), ('GAUTENG,Soshanguve', 'GAUTENG,Soshanguve'), ('GAUTENG,Pretoria', 'GAUTENG,Pretoria'), ('GAUTENG,Centurion', 'GAUTENG,Centurion'), ('LIMPOPO,Bela Bela', 'LIMPOPO,Bela Bela'), ('LIMPOPO,Modimolle', 'LIMPOPO,Modimolle'), ('LIMPOPO,Polokwane', 'LIMPOPO,Polokwane'), ('CAPE TOWN', 'CAPE TOWN'), ('DURBAN', 'DURBAN')], default='GAUTENG', max_length=50),
        ),
    ]
