# Generated by Django 3.0.5 on 2022-06-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220607_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(blank=True, default='static/images/default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='img',
            field=models.ImageField(blank=True, default='static/images/default.png', null=True, upload_to=''),
        ),
    ]
